site_name: RapidCopy
theme:
  name: material
  language: en
  palette:
    scheme: preference
    primary: teal
    accent: teal
    font: false
  logo: images/logo.png
  favicon: images/favicon.png
markdown_extensions:
  - admonition
  - codehilite:
      guess_lang: false
  - toc:
      permalink: true
repo_name: rccypher/RapidCopy
repo_url: https://github.com/rccypher/RapidCopy
nav:
  - Home: index.md
  - Installation: install.md
  - Usage: usage.md
  - FAQ: faq.md
